Remove c7 support
ome/omero-certificates pull request #54
Opened 2024-12-16 18:36 UTC by jburel

C7 has now been removed

2024-12-16 21:23 UTC, sbesson reviewed
This PR primarily the changes originally introduced in https://github.com/ome/omero-certificates/pull/36 and amended in https://github.com/ome/omero-certificates/pull/38. 

A few questions that might be answered by the functional testing:
- what is the main motivation for the cipher change from `HIGH` to `HIGH:!DHE` which was not part of #36?
- is there any value in keeping `omero.glacier2.IceSSL.DH.2048` as this property was set independently of the underlying platform?
- should the changes in `setup.py` and `README.md` also be reverted/updated?


As for the the original work, extensive testing will need to be put into place to test various combinations of server/clients under the current supported platforms.

2024-12-16 22:27 UTC, jburel commented
> This PR primarily the changes originally introduced in #36 and amended in #38.
> 
> A few questions that might be answered by the functional testing:
> 
> * what is the main motivation for the cipher change from `HIGH` to `HIGH:!DHE` which was not part of [Allow TLS 1.3 and use ffdhe2048 DHE group #36](https://github.com/ome/omero-certificates/pull/36)?

Mainly, a follow-up from security report. Open for discussion
> * is there any value in keeping `omero.glacier2.IceSSL.DH.2048` as this property was set independently of the underlying platform?
Missed when cleaning
> * should the changes in `setup.py` and `README.md` also be reverted/updated?
yes
> 
> As for the the original work, extensive testing will need to be put into place to test various combinations of server/clients under the current supported platforms.

2025-01-28 12:13 UTC, sbesson requested changes
In the same spirit as the review of https://github.com/ome/omero-certificates/pull/36, OMERO.server 5.6.14 was deployed in a minimal set of Docker environments for the actively support operating systems (Rocky Linux 8, Rocky Linux 9, Ubuntu 22.04, Ubuntu 24.04).

The SSL connection was tested for all combinations of clients/servers using:
- a simple Python connect script with `IceSS.Trace.Security` set to 1
- a simple OMERO import workflow

In all scenarios, the TLS 1.3 protocol with the `TLS_AES_256_GCM_SHA384` Cipher was negotiated with the server. Both the connection and the import worked without issue.

Overall the changes are consistent with the removal of support for CentOS 7 last year. The tightening of the default ciphers seems to have no negative impact on clients.

Note the testing above was only performed on a limited set of clients. Is it worth setting up a testing environment and including additional reviews from the OME team to widen the testing on other environments including OSX and Windows? Should CentOS 7 still be tested as a client? And thinking of upgrade, would you recommend the cipher changes since the current plugin will keep existing ciphers if set in the configuration? 
/cc @chris-allan @stick

2025-01-28 12:18 UTC, jburel commented on README.md
>  - `omero.glacier2.IceSSL.Ciphers=HIGH`: the default weaker ciphers may not be supported on some systems
Do we agree to use ``HIGH:!DHE``? I was going to revert my commit following the previous comment.
If we agree then I will update the readme accordingly

2025-01-28 12:37 UTC, sbesson commented on README.md
>  - `omero.glacier2.IceSSL.Ciphers=HIGH`: the default weaker ciphers may not be supported on some systems
If I am not mistaken, this configuration has been deployed on a number of OMERO deployments including the demo server and the institutional University of Dundee OMERO - https://github.com/ome/prod-playbooks/pull/384. Has anyone reported any connection issue from any client in particular desktop clients?

Assuming the answer is no, this would complement the testing above and suggest the configuration is safe to deploy and hardens the application to remove ciphers which may been flagged by some security reports and should no longer be negotiated anyways.

As mentioned in my review, to be on the safe side, it would be useful to a complete  list of the client environments that have already been evaluated against these changes to identify and test any gaps before moving to production.

2025-01-28 13:06 UTC, jburel commented on README.md
>  - `omero.glacier2.IceSSL.Ciphers=HIGH`: the default weaker ciphers may not be supported on some systems
It has been deployed yes, following the security reports.
No issues reported

2025-01-29 13:54 UTC, sbesson approved these changes

2025-02-17 10:00 UTC, merged